TrainingApplication/Models/Course.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TrainingApplication.Models
{
    public class Course
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(255)]
        public string Name { get; set; }
        [Required]
        public string Description { get; set; }

        [ForeignKey("Category")]
        public int CategoryId { get; set; }
        public Category Category { get; set; }
    }
}

TrainingApplication/Models/Trainee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TrainingApplication.Models
{
    public class Trainee
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        [StringLength(255)]
        public string Name { get; set; }
        [Required]
        public int Age { get; set; }
        [Required]
        public DateTime DateOfBirth { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        public string Education { get; set; }

        [ForeignKey("User")]
        public String TraineeId { get; set; }
        public ApplicationUser User { get; set; }
    }
}

TrainingApplication/Controllers/TraineeController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrainingApplication.Models;
using TrainingApplication.Utils;
using TrainingApplication.ViewModels;

namespace TrainingApplication.Controllers
{
    [Authorize(Roles = Role.Trainee)]
    public class TraineeController : Controller
    {
        private ApplicationDbContext _context;
        public TraineeController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: Trainee
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var traineeInDb = _context.Trainees
                .SingleOrDefault(t => t.TraineeId == userId);
            return View(traineeInDb);
        }

        [HttpGet]
        public ActionResult Courses()
        {
            var userId = User.Identity.GetUserId();
            var category = _context.Categories.ToList();
            var courses = _context.TraineesCourses
                .Where(t => t.Trainee.TraineeId == userId)
                .Select(t => t.Course)
                .ToList();
            return View(courses);
        }

        [HttpGet]
        public ActionResult CourseTrainees(int id)
        {
            var traineesCourse = _context.TraineesCourses
                .Where(t => t.CourseId == id)
                .Select(t => t.Trainee)
                .ToList();
            return View(traineesCourse);
        }
    }
}

TrainingApplication/Views/Trainee/CourseTrainees.cshtml
@model IEnumerable<TrainingApplication.Models.Trainee>
@{
    ViewBag.Title = "CourseTrainees";
}

<h2>trainees in Course</h2>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Trainees</th>
            <th scope="col">Email</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in @Model)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.Email</td>
            </tr>
        }
    </tbody>
</table>

TrainingApplication/Views/Trainee/Courses.cshtml
@model IEnumerable<TrainingApplication.Models.Course>
@{
    ViewBag.Title = "Course";
}

<h2>Courses</h2>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Course</th>
            <th scope="col">Description</th>
            <th scope="col">Category</th>
            <th scope="col">Trainees</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in @Model)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.Description</td>
                <td>@item.Category.Name</td>
                <td>
                    @Html.ActionLink("Trainees", "CourseTrainees", "Trainee", new { id = item.Id }, new { @class = "btn btn-success" })
                </td>
            </tr>
        }
    </tbody>
</table>

TrainingApplication/Views/Trainee/Index.cshtml
@model TrainingApplication.Models.Trainee
    @{
        ViewBag.Title = "Index";
    }

<h2> @Model.Name Profile</h2>

    <div class="panel panel-default">
        <div class="panel-heading">
            @Model.Name
        </div>
        <div class="panel-body">
            <p>Age: @Model.Age</p>
            <p>Birthday: @Model.DateOfBirth.ToString("d")</p>
            <p>Address: @Model.Address</p>
            <p>Education: @Model.Education</p>
        </div>
    </div>